<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapping" nsURI="http://org.gravity.mapping.secdfd/mapping" nsPrefix="org.gravity.mapping.secdfd.model">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.gravity.mapping.secdfd.model"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userdefined" upperBound="-1"
        eType="ecore:EClass Secdfd.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ignored" upperBound="-1"
        eType="ecore:EClass Secdfd.ecore#//AbstractCorrespondence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggested" upperBound="-1"
        eType="ecore:EClass Secdfd.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accepted" upperBound="-1"
        eType="ecore:EClass Secdfd.ecore#//AbstractCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondences" ordered="false"
        upperBound="-1" eType="ecore:EClass Secdfd.ecore#//AbstractCorrespondence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMappingDerived" abstract="true"
      eSuperTypes="Secdfd.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="derived" upperBound="-1"
        eType="#//AbstractMappingBase" eOpposite="#//AbstractMappingBase/deriving"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingProcessName" eSuperTypes="Secdfd.ecore#//Method2Element #//AbstractMappingRanking #//AbstractMappingBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingProcessSignature" eSuperTypes="Secdfd.ecore#//Signature2Element #//AbstractMappingDerived #//AbstractMappingBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingProcessDefinition" eSuperTypes="Secdfd.ecore#//Defintion2Element #//AbstractMappingDerived #//AbstractMappingBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMappingRanking" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ranking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingEntityType" eSuperTypes="Secdfd.ecore#//Type2NamedEntity #//AbstractMappingRanking #//AbstractMappingBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMappingBase" abstract="true"
      interface="true" eSuperTypes="Secdfd.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deriving" upperBound="-1"
        eType="#//AbstractMappingDerived" eOpposite="#//AbstractMappingDerived/derived"/>
  </eClassifiers>
</ecore:EPackage>
