<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="secdfd" nsURI="platform:/plugin/org.gravity.mapping.secdfd/model/Secdfd.ecore"
    nsPrefix="org.gravity.mapping.secdfd">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.gravity.mapping"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Method2Element" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.gravity.org/typegraph/basic#//TMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/eDFDFlowTracking1/model/eDFDFlowTracking1.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type2NamedEntity" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.gravity.org/typegraph/basic#//TAbstractType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/eDFDFlowTracking1/model/eDFDFlowTracking1.ecore#//NamedEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeGraph2EDFD" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.gravity.org/typegraph/basic#//TypeGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/eDFDFlowTracking1/model/eDFDFlowTracking1.ecore#//EDFD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Defintion2Element" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.gravity.org/typegraph/basic#//TMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/eDFDFlowTracking1/model/eDFDFlowTracking1.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow2Access" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.gravity.org/typegraph/basic#//TAccess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/eDFDFlowTracking1/model/eDFDFlowTracking1.ecore#//Flow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature2Element" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.gravity.org/typegraph/basic#//TSignature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/resource/eDFDFlowTracking1/model/eDFDFlowTracking1.ecore#//Element"/>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="platform:/plugin/org.gravity.mapping.secdfd/model/Secdfd.ecore#//Rules"
      nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="TypeGraph2EDFD" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
  </eSubpackages>
</ecore:EPackage>
