/**
 * generated by Xtext 2.17.1
 */
package org.secdfd.dsl;

import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import org.secdfd.model.ModelPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SecDFDStandaloneSetup extends SecDFDStandaloneSetupGenerated {
  public static void doSetup() {
    new SecDFDStandaloneSetup().createInjectorAndDoEMFRegistration();
  }

  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey("http://www.secdfd.org/secdfd");
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put(ModelPackage.eNS_URI, ModelPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
