/**
 * generated by Xtext 2.17.1
 */
package org.secdfd.dsl.scoping;

import org.secdfd.dsl.scoping.AbstractSecDFDScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SecDFDScopeProvider extends AbstractSecDFDScopeProvider {
}
