/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.mydsl;

import com.google.inject.Injector;
import eDFDFlowTracking.EDFDFlowTrackingPackage;
import org.eclipse.emf.ecore.EPackage;
import org.xtext.example.mydsl.MyDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslStandaloneSetup extends MyDslStandaloneSetupGenerated {
  public static void doSetup() {
    new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey("http://www.example.org/eDFDFlowTracking");
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put(EDFDFlowTrackingPackage.eNS_URI, EDFDFlowTrackingPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
