/*
 * generated by Xtext 2.20.0
 */
package org.secdfd.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SecDFDAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/secdfd/dsl/parser/antlr/internal/InternalSecDFD.tokens");
	}
}
