/*
 * generated by Xtext 2.20.0
 */
package org.secdfd.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.secdfd.dsl.parser.antlr.internal.InternalSecDFDParser;
import org.secdfd.dsl.services.SecDFDGrammarAccess;

public class SecDFDParser extends AbstractAntlrParser {

	@Inject
	private SecDFDGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSecDFDParser createParser(XtextTokenStream stream) {
		return new InternalSecDFDParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EDFD";
	}

	public SecDFDGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SecDFDGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
