/*
 * generated by Xtext 2.20.0
 */
package org.secdfd.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSecDFDScopeProvider extends DelegatingScopeProvider {
}
