/*
 * generated by Xtext 2.37.0
 */
package org.secdfd.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SecDFDUiModule extends AbstractSecDFDUiModule {

	public SecDFDUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
