/*
 * generated by Xtext 2.20.0
 */
package org.secdfd.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class SecDFDUiModule extends AbstractSecDFDUiModule {
}
