/*
 * generated by Xtext 2.37.0
 */
package org.secdfd.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.secdfd.dsl.SecDFDRuntimeModule;
import org.secdfd.dsl.SecDFDStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SecDFDIdeSetup extends SecDFDStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SecDFDRuntimeModule(), new SecDFDIdeModule()));
	}
	
}
