/*
 * generated by Xtext 2.20.0
 */
package org.secdfd.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.secdfd.dsl.ui.internal.DslActivator;

public class SecDFDUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.secdfd.dsl.SecDFD");
	}

}
