package crypto;

import java.security.InvalidKeyException;
import java.security.*;
import javax.crypto.*;
import javax.crypto.spec.*;

public class DES // authority(DESprin)
{
	/**
	 * returns a newly generated key for use in DES encryption
	 * @return a DES Key
	 */
    static public Key getNewKey() throws NoSuchAlgorithmException, NullPointerException
    {
    		return KeyGenerator.getInstance("DES").generateKey();
    }

    /** 
     * encrypts a String using a previously generated DES Key
     * @param key a previously generated DES Key (e.g. made with DES.getNewKey()
     * @param s the String to encrypt
     * @return a new Ciphertext object which contains both the key and the needed IV
     */
    static public Ciphertext encrypt(Key key, String s)
    //         throws (InvalidKeyException, IllegalBlockSizeException, NullPointerException,
    //		 BadPaddingException, NoSuchAlgorithmException, NoSuchPaddingException)
//	 where oneway(DESprin,P)
    {
		Ciphertext ciphertext = null;
	
		try {
		    Cipher desCipher_ = Cipher.getInstance("DES/CBC/PKCS5Padding");
		    
		    desCipher_.init(Cipher.ENCRYPT_MODE,key);
		    
		    final byte[] input = s.getBytes();
		    final byte[] encrypted = desCipher_.doFinal(input);
		    
		    ciphertext = new Ciphertext(encrypted, desCipher_.getIV());
		}
		catch (Exception e) {}

	return ciphertext;
    }

    /** 
     * encrypts a String using a previously generated DES Key
     * @param key a previously generated DES Key (e.g. made with DES.getNewKey()
     * @param s the String to encrypt
     * @return a new Ciphertext object which contains both the key and the needed IV
     */
    static public Ciphertext encrypt(Key key, byte[] input)
    //         throws (InvalidKeyException, IllegalBlockSizeException, NullPointerException,
    //		 BadPaddingException, NoSuchAlgorithmException, NoSuchPaddingException)
//	 where oneway(DESprin,P)
    {
		Ciphertext ciphertext = null;
	
		try {
		    Cipher desCipher_ = Cipher.getInstance("DES/CBC/PKCS5Padding");
		    
		    desCipher_.init(Cipher.ENCRYPT_MODE,key);
		    
		    final byte[] encrypted = desCipher_.doFinal(input);
		    
//		    ciphertext = new Ciphertext(new String(encrypted), new String(desCipher_.getIV()));
		    ciphertext = new Ciphertext(encrypted, desCipher_.getIV());
		}
		catch (Exception e) {}

	return ciphertext;
    }

    /**
     * Decrypts a Ciphertext given a Key, using the DES algorithm
     * @param key the correct key for the given ciphertext
     * @param ciph must be a Ciphertext with the correct IV (e.g., generated by DES.encrypt)
     * @return the plaintext corresponding to the ciphertext
     */
    static public String decrypt(Key key, Ciphertext ciph) 
	 throws InvalidKeyException, IllegalBlockSizeException, BadPaddingException, 
		 NoSuchPaddingException, InvalidAlgorithmParameterException, 
		 NoSuchAlgorithmException, NullPointerException
    {
		Cipher desCipher_ = Cipher.getInstance("DES/CBC/PKCS5Padding");
	
		desCipher_.init(Cipher.DECRYPT_MODE,key,new IvParameterSpec(ciph.iv));//.getBytes()));
		    
		//byte[] encrypted = ciph.encText.getBytes();
		String output = new String(desCipher_.doFinal(ciph.encText));
	
		return output;
    }
}