/*
 * generated by Xtext 2.20.0
 */
package org.secdfd.dsl.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class SecDFDOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
